#!/usr/bin/env python3
"""
migrate.py — Radiance ERP MongoDB -> Supabase ETL orchestrator.

Reads all 19 MongoDB collections, builds a global ObjectId->UUID lookup table,
applies per-collection transform functions, and writes one SQL INSERT file per
Supabase table to migration/output/. Files are named with FK-order numeric
prefixes so they can be loaded in sequence with no FK violations.

Usage:
  cd /path/to/project/   (project root, not migration/)
  cp migration/.env.migration.example migration/.env.migration
  # Edit migration/.env.migration with real credentials
  python migration/migrate.py             # full run
  python migration/migrate.py --dry-run  # print counts only, no files written

Output files (in migration/output/):
  02_profiles.sql
  03_companies.sql
  04_contacts.sql
  05_pipeline_stages.sql
  06_deals.sql
  07_tasks.sql
  08_notes.sql
  09a_accounts_first_pass.sql     (all accounts with parent_id = NULL)
  09b_accounts_parent_update.sql  (UPDATE statements to restore parent_id)
  10_invoices.sql
  11_invoice_items.sql
  12_quotes.sql
  13_payments.sql
  14_journal_entries.sql
  15_journal_lines.sql
  16_departments.sql
  17_employees.sql
  18_leave_requests.sql
  19_payslips.sql
  20_google_tokens.sql
  21_audit_logs.sql

  migration/id_map.json  (ObjectId -> UUID mapping, useful for debugging)

Notes:
  - auth.users (file 01) is handled by load_users.py (plan 04-02), not here.
  - search_vector columns are never included (they are PostgreSQL generated columns).
  - accounts requires two passes: 09a inserts with parent_id=NULL, 09b updates.
  - payslips are deduplicated on (employee_id, period_month, period_year) to
    satisfy the Supabase UNIQUE constraint.
  - All SQL files use ON CONFLICT DO NOTHING for idempotent re-runs.
"""

import os
import sys
import json
import argparse
from dotenv import load_dotenv

# Load .env.migration from the current working directory.
# Run this script from the project root: python migration/migrate.py
load_dotenv("migration/.env.migration")

from migration.extract import extract_all, COLLECTIONS
from migration.utils import build_id_map, escape
from migration.transform import (
    transform_profile,
    transform_company,
    transform_contact,
    transform_pipeline_stage,
    transform_deal,
    transform_task,
    transform_note,
    transform_invoice,
    transform_invoice_item,
    transform_quote,
    transform_payment,
    transform_account,
    transform_journal_entry,
    transform_journal_line,
    transform_department,
    transform_employee,
    transform_leave_request,
    transform_payslip,
    transform_google_token,
    transform_audit_log,
    deduplicate_payslips,
)

OUTPUT_DIR = "migration/output"


# ---------------------------------------------------------------------------
# SQL file writer
# ---------------------------------------------------------------------------

def write_sql_file(
    filename: str,
    table: str,
    rows: list,
    columns: list,
    dry_run: bool = False,
) -> int:
    """Write rows as a single INSERT ... VALUES statement to a .sql file.

    Args:
        filename: output filename (e.g. '03_companies.sql')
        table:    fully qualified table name (e.g. 'public.companies')
        rows:     list of dicts from transform functions
        columns:  ordered list of column names to include in the INSERT.
                  MUST NOT include 'search_vector' or '_mongo_*' staging fields.
        dry_run:  if True, only print the count — do not write any files.

    Returns:
        Number of rows that would be / were written.

    Critical: columns list must never contain 'search_vector'.
    That column is a PostgreSQL GENERATED ALWAYS AS ... STORED column.
    Attempting to insert it raises: ERROR: cannot insert into column "search_vector".
    """
    count = len(rows)
    if count == 0:
        print(f"  [SKIP] {table} — 0 rows")
        return 0

    if dry_run:
        print(f"  [DRY]  {filename:<45} {count:>6} rows  (table: {table})")
        return count

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, filename)

    col_list = ", ".join(columns)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"-- Table: {table} ({count} rows)\n")
        f.write(f"-- Generated by migration/migrate.py\n")
        f.write(f"-- Load with: psql $SUPABASE_DB_DSN -f {filename}\n\n")
        f.write(f"INSERT INTO {table} ({col_list}) VALUES\n")
        value_lines = []
        for row in rows:
            vals = [escape(row.get(col)) for col in columns]
            value_lines.append(f"  ({', '.join(vals)})")
        f.write(",\n".join(value_lines))
        f.write("\nON CONFLICT DO NOTHING;\n")

    print(f"  [OK]   {path:<55} {count:>6} rows")
    return count


# ---------------------------------------------------------------------------
# Accounts second-pass UPDATE writer
# ---------------------------------------------------------------------------

def write_accounts_parent_update(
    account_rows: list,
    id_map: dict,
    dry_run: bool = False,
) -> int:
    """Write UPDATE statements to restore parent_id on self-referencing accounts.

    The first pass (09a) inserts all accounts with parent_id = NULL to avoid
    FK violations on the self-reference. This second pass writes UPDATE statements
    that set parent_id to the correct UUID for accounts that had a parent in MongoDB.

    Args:
        account_rows: list of dicts from transform_account (contains _mongo_parent_id)
        id_map:       global ObjectId -> UUID lookup table
        dry_run:      if True, only print the count.

    Returns:
        Number of UPDATE statements that would be / were written.
    """
    update_lines = []
    for row in account_rows:
        mongo_parent = row.get("_mongo_parent_id")
        if mongo_parent and mongo_parent in id_map:
            parent_uuid = id_map[mongo_parent]
            account_uuid = row["id"]
            update_lines.append(
                f"UPDATE public.accounts SET parent_id = '{parent_uuid}' "
                f"WHERE id = '{account_uuid}';"
            )

    count = len(update_lines)
    if dry_run:
        print(f"  [DRY]  09b_accounts_parent_update.sql            {count:>6} UPDATE statements")
        return count

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, "09b_accounts_parent_update.sql")
    with open(path, "w", encoding="utf-8") as f:
        f.write("-- Second pass: restore parent_id on self-referencing accounts\n")
        f.write("-- Generated by migration/migrate.py\n")
        f.write("-- Run AFTER 09a_accounts_first_pass.sql\n\n")
        if update_lines:
            f.write("\n".join(update_lines))
            f.write("\n")
        else:
            f.write("-- No accounts had a parent_id — nothing to update.\n")

    print(f"  [OK]   {path:<55} {count:>6} UPDATE statements")
    return count


# ---------------------------------------------------------------------------
# Main orchestrator
# ---------------------------------------------------------------------------

def main(dry_run: bool = False):
    if dry_run:
        print("=== DRY RUN MODE — no files will be written ===\n")

    # ------------------------------------------------------------------
    # Step 1: Extract all documents from MongoDB
    # ------------------------------------------------------------------
    print("=== Step 1: Extract from MongoDB ===")
    data = extract_all()

    # ------------------------------------------------------------------
    # Step 2: Build the global id_map from ALL collections before any
    # transform runs. This ensures that FK references from any collection
    # to any other collection (even across tables) resolve correctly.
    # ------------------------------------------------------------------
    print("\n=== Step 2: Build combined id_map (all collections) ===")
    id_map = {}
    for col in COLLECTIONS:
        col_map = build_id_map(data[col])
        id_map.update(col_map)
    print(f"  Total IDs mapped: {len(id_map)}")

    if not dry_run:
        os.makedirs("migration", exist_ok=True)
        with open("migration/id_map.json", "w", encoding="utf-8") as f:
            json.dump(id_map, f, indent=2)
        print("  id_map.json written to migration/id_map.json")

    # ------------------------------------------------------------------
    # Step 3: Transform each collection and write SQL files in FK order.
    #
    # File 01 (auth.users) is NOT written here — it is handled by
    # load_users.py (plan 04-02) which calls the Supabase Admin API.
    #
    # IMPORTANT: No column list below may include 'search_vector'.
    # search_vector is a PostgreSQL GENERATED ALWAYS AS ... STORED column.
    # Inserting it raises: ERROR: cannot insert into column "search_vector"
    # ------------------------------------------------------------------
    print("\n=== Step 3: Transform + write SQL files (FK order) ===")

    total_rows = 0

    # 02 — profiles (from users collection; auth.users created separately)
    rows = [transform_profile(d, id_map) for d in data["users"]]
    total_rows += write_sql_file(
        "02_profiles.sql", "public.profiles", rows,
        ["id", "full_name", "avatar_url", "role",
         "failed_login_attempts", "locked_until",
         "created_at", "updated_at"],
        dry_run=dry_run,
    )

    # 03 — companies
    rows = [transform_company(d, id_map) for d in data["companies"]]
    total_rows += write_sql_file(
        "03_companies.sql", "public.companies", rows,
        ["id", "owner_id", "name", "industry", "website", "address",
         "created_at", "updated_at", "deleted_at"],
        # NOTE: search_vector intentionally excluded
        dry_run=dry_run,
    )

    # 04 — contacts
    rows = [transform_contact(d, id_map) for d in data["contacts"]]
    total_rows += write_sql_file(
        "04_contacts.sql", "public.contacts", rows,
        ["id", "owner_id", "first_name", "last_name", "email", "phone",
         "company_id", "company_name", "tags", "notes",
         "created_at", "updated_at", "deleted_at"],
        # NOTE: search_vector intentionally excluded
        dry_run=dry_run,
    )

    # 05 — pipeline_stages
    rows = [transform_pipeline_stage(d, id_map) for d in data["pipeline_stages"]]
    total_rows += write_sql_file(
        "05_pipeline_stages.sql", "public.pipeline_stages", rows,
        ["id", "owner_id", "name", "position", "created_at"],
        dry_run=dry_run,
    )

    # 06 — deals
    rows = [transform_deal(d, id_map) for d in data["deals"]]
    total_rows += write_sql_file(
        "06_deals.sql", "public.deals", rows,
        ["id", "owner_id", "title", "value", "stage_id", "contact_id",
         "company_id", "assigned_to", "closed_at",
         "created_at", "updated_at", "deleted_at"],
        # NOTE: search_vector intentionally excluded
        dry_run=dry_run,
    )

    # 07 — tasks
    rows = [transform_task(d, id_map) for d in data["tasks"]]
    total_rows += write_sql_file(
        "07_tasks.sql", "public.tasks", rows,
        ["id", "owner_id", "title", "description", "due_date",
         "completed", "completed_at", "contact_id", "deal_id",
         "assigned_to", "created_at", "updated_at", "deleted_at"],
        dry_run=dry_run,
    )

    # 08 — notes
    rows = [transform_note(d, id_map) for d in data["notes"]]
    total_rows += write_sql_file(
        "08_notes.sql", "public.notes", rows,
        ["id", "owner_id", "content", "contact_id", "company_id",
         "deal_id", "created_at", "updated_at", "deleted_at"],
        dry_run=dry_run,
    )

    # 09a — accounts first pass (parent_id = NULL to avoid self-FK violation)
    account_rows = [transform_account(d, id_map) for d in data["accounts"]]
    total_rows += write_sql_file(
        "09a_accounts_first_pass.sql", "public.accounts", account_rows,
        # _mongo_parent_id is a staging key — MUST NOT be in the column list
        ["id", "owner_id", "code", "name", "type", "parent_id",
         "created_at", "updated_at"],
        dry_run=dry_run,
    )

    # 09b — accounts second pass: UPDATE parent_id using id_map
    write_accounts_parent_update(account_rows, id_map, dry_run=dry_run)

    # 10 — invoices
    rows = [transform_invoice(d, id_map) for d in data["invoices"]]
    total_rows += write_sql_file(
        "10_invoices.sql", "public.invoices", rows,
        ["id", "owner_id", "invoice_number", "contact_id", "company_id",
         "status", "issue_date", "due_date", "subtotal", "tax_rate",
         "tax_amount", "total", "amount_paid", "notes",
         "stripe_payment_intent_id", "created_at", "updated_at", "deleted_at"],
        dry_run=dry_run,
    )

    # 11 — invoice_items (child of invoices)
    rows = [transform_invoice_item(d, id_map) for d in data["invoice_items"]]
    total_rows += write_sql_file(
        "11_invoice_items.sql", "public.invoice_items", rows,
        ["id", "invoice_id", "description", "quantity", "unit_price", "total"],
        dry_run=dry_run,
    )

    # 12 — quotes
    rows = [transform_quote(d, id_map) for d in data["quotes"]]
    total_rows += write_sql_file(
        "12_quotes.sql", "public.quotes", rows,
        ["id", "owner_id", "quote_number", "contact_id", "status",
         "valid_until", "subtotal", "tax_rate", "total",
         "converted_to_invoice_id", "created_at", "updated_at", "deleted_at"],
        dry_run=dry_run,
    )

    # 13 — payments
    rows = [transform_payment(d, id_map) for d in data["payments"]]
    total_rows += write_sql_file(
        "13_payments.sql", "public.payments", rows,
        ["id", "owner_id", "invoice_id", "amount", "method", "paid_at",
         "reference", "created_at"],
        dry_run=dry_run,
    )

    # 14 — journal_entries
    rows = [transform_journal_entry(d, id_map) for d in data["journal_entries"]]
    total_rows += write_sql_file(
        "14_journal_entries.sql", "public.journal_entries", rows,
        ["id", "owner_id", "date", "description", "invoice_id",
         "payment_id", "created_at"],
        dry_run=dry_run,
    )

    # 15 — journal_lines (child of journal_entries + accounts)
    rows = [transform_journal_line(d, id_map) for d in data["journal_lines"]]
    total_rows += write_sql_file(
        "15_journal_lines.sql", "public.journal_lines", rows,
        ["id", "journal_entry_id", "account_id", "debit", "credit",
         "description"],
        dry_run=dry_run,
    )

    # 16 — departments
    rows = [transform_department(d, id_map) for d in data["departments"]]
    total_rows += write_sql_file(
        "16_departments.sql", "public.departments", rows,
        ["id", "owner_id", "name", "created_at", "updated_at", "deleted_at"],
        dry_run=dry_run,
    )

    # 17 — employees
    rows = [transform_employee(d, id_map) for d in data["employees"]]
    total_rows += write_sql_file(
        "17_employees.sql", "public.employees", rows,
        ["id", "owner_id", "full_name", "email", "job_title",
         "department_id", "base_salary", "start_date", "status",
         "created_at", "updated_at", "deleted_at"],
        dry_run=dry_run,
    )

    # 18 — leave_requests
    rows = [transform_leave_request(d, id_map) for d in data["leave_requests"]]
    total_rows += write_sql_file(
        "18_leave_requests.sql", "public.leave_requests", rows,
        ["id", "owner_id", "employee_id", "type", "start_date", "end_date",
         "status", "approved_by", "notes", "created_at", "updated_at"],
        dry_run=dry_run,
    )

    # 19 — payslips (deduplicated on employee_id + period_month + period_year)
    payslip_rows = deduplicate_payslips(
        [transform_payslip(d, id_map) for d in data["payslips"]]
    )
    total_rows += write_sql_file(
        "19_payslips.sql", "public.payslips", payslip_rows,
        ["id", "owner_id", "employee_id", "period_month", "period_year",
         "gross_salary", "cnas_deduction", "irg_deduction", "net_salary",
         "generated_at"],
        dry_run=dry_run,
    )

    # 20 — google_tokens
    rows = [transform_google_token(d, id_map) for d in data["google_tokens"]]
    total_rows += write_sql_file(
        "20_google_tokens.sql", "public.google_tokens", rows,
        ["id", "user_id", "access_token", "refresh_token", "expires_at",
         "scopes", "created_at", "updated_at"],
        dry_run=dry_run,
    )

    # 21 — audit_logs
    rows = [transform_audit_log(d, id_map) for d in data["audit_logs"]]
    total_rows += write_sql_file(
        "21_audit_logs.sql", "public.audit_logs", rows,
        ["id", "user_id", "action", "resource", "resource_id",
         "metadata", "ip_address", "created_at"],
        dry_run=dry_run,
    )

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print(f"\n=== {'Dry run' if dry_run else 'Done'} ===")
    print(f"Total rows processed: {total_rows}")
    if not dry_run:
        print(f"SQL files written to: {OUTPUT_DIR}/")
        print(f"id_map saved to:      migration/id_map.json")
        print()
        print("Next steps:")
        print("  1. Run load_users.py to import users into auth.users (plan 04-02)")
        print("  2. Load SQL files in order:")
        print(f"     for f in $(ls {OUTPUT_DIR}/*.sql | sort); do")
        print(f"       psql \"$SUPABASE_DB_DSN\" -f \"$f\"")
        print(f"     done")
        print("  3. Run validate.py to check record counts and FK integrity (plan 04-03)")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Radiance ERP — MongoDB to Supabase ETL migration script.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python migration/migrate.py              # full run — write SQL files
  python migration/migrate.py --dry-run   # print counts only, no files written

Environment (set in migration/.env.migration):
  MONGO_URI         MongoDB Atlas SRV connection string
  SUPABASE_DB_DSN   PostgreSQL direct connection string (postgres superuser)
        """,
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Print row counts only — do not connect to MongoDB or write any files.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    main(dry_run=args.dry_run)
