"""
Analytics models — AI scoring, KPI snapshots, insights.
MongoEngine Documents only.
"""
import mongoengine as me
from datetime import datetime

KPI_PERIOD = ('daily', 'weekly', 'monthly', 'quarterly', 'yearly')
INSIGHT_TYPE = ('deal_risk', 'revenue_forecast', 'churn_risk', 'upsell_opportunity', 'general')
INSIGHT_SEVERITY = ('info', 'warning', 'critical')


class DealScore(me.Document):
    """
    AI-generated win probability score for a deal.
    Recalculated by the Celery task apps.analytics.tasks.recalculate_deal_scores.
    """
    deal_id = me.StringField(required=True, unique=True)
    deal_title = me.StringField(null=True)
    contact_id = me.StringField(null=True)
    stage = me.StringField(null=True)
    value = me.FloatField(default=0)

    # ML features
    days_in_stage = me.IntField(default=0)
    tasks_completed = me.IntField(default=0)
    notes_count = me.IntField(default=0)
    messages_count = me.IntField(default=0)
    emails_count = me.IntField(default=0)
    meetings_count = me.IntField(default=0)

    # Score & prediction
    win_probability = me.FloatField(min_value=0.0, max_value=1.0, default=0.2)
    revenue_forecast = me.FloatField(default=0)
    risk_level = me.StringField(choices=('low', 'medium', 'high'), default='medium')
    model_version = me.StringField(default='v1')
    scored_at = me.DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'deal_scores',
        'ordering': ['-scored_at'],
        'indexes': ['deal_id', 'win_probability', 'risk_level'],
    }

    def __str__(self):
        return f'Score for {self.deal_title}: {self.win_probability:.0%}'


class KPISnapshot(me.Document):
    """Periodic KPI snapshot for dashboard charts."""
    period = me.StringField(choices=KPI_PERIOD, default='daily')
    snapshot_date = me.DateTimeField(required=True)
    # Sales
    new_deals = me.IntField(default=0)
    deals_won = me.IntField(default=0)
    deals_lost = me.IntField(default=0)
    revenue_generated = me.FloatField(default=0)
    avg_deal_value = me.FloatField(default=0)
    win_rate = me.FloatField(default=0)    # 0-1
    # CRM activity
    new_contacts = me.IntField(default=0)
    new_companies = me.IntField(default=0)
    tasks_completed = me.IntField(default=0)
    # Communication
    whatsapp_messages_sent = me.IntField(default=0)
    whatsapp_messages_received = me.IntField(default=0)
    emails_sent = me.IntField(default=0)
    # Billing
    invoices_issued = me.IntField(default=0)
    invoices_paid = me.IntField(default=0)
    invoices_overdue = me.IntField(default=0)
    total_billed = me.FloatField(default=0)
    created_at = me.DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'kpi_snapshots',
        'ordering': ['-snapshot_date'],
        'indexes': ['period', 'snapshot_date'],
    }

    def __str__(self):
        return f'KPI {self.period} — {self.snapshot_date}'


class AIInsight(me.Document):
    """
    AI-generated text insight / recommendation for a user or manager.
    Generated by Claude (Anthropic) or derived from rule-based scoring.
    """
    insight_type = me.StringField(choices=INSIGHT_TYPE, default='general')
    severity = me.StringField(choices=INSIGHT_SEVERITY, default='info')
    title = me.StringField(required=True, max_length=300)
    body = me.StringField(required=True)
    recommendation = me.StringField(null=True)
    # Context references
    related_deal_id = me.StringField(null=True)
    related_contact_id = me.StringField(null=True)
    target_user_id = me.StringField(null=True)
    # Lifecycle
    is_read = me.BooleanField(default=False)
    is_dismissed = me.BooleanField(default=False)
    expires_at = me.DateTimeField(null=True)
    generated_at = me.DateTimeField(default=datetime.utcnow)

    meta = {
        'collection': 'ai_insights',
        'ordering': ['-generated_at'],
        'indexes': ['insight_type', 'severity', 'target_user_id', 'is_dismissed'],
    }

    def __str__(self):
        return f'[{self.severity}] {self.title}'
